WebApplication1/Controllers/AdvertisementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using Microsoft.AspNet.Identity;

namespace WebApplication1.Controllers
{
    public class AdvertisementController : Controller
    {
        private ImageController _imageController;

        public ActionResult RegisterAdvertisement(AdvertisementMessageId? message)
        {
            ViewBag.Message = "Petcare.";
            ViewBag.result =
                message == AdvertisementMessageId.AddAdvertiseSuccess ? "Votre annonce à été créé."
                : message == AdvertisementMessageId.Error ? "Erreur."
                : "";

            if (!Request.IsAuthenticated)
            {
                ViewBag.status = "Vous devez être connecté pour créer une annonce.";
            }
            return View();
        }

        //
        // POST: /Advertisment/RegisterAdvertisment
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterAdvertisement(AdvertisementModel model, HttpPostedFileBase file)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    string userId = User.Identity.GetUserId();

                    //animal 
                    AnimalModel animal = new AnimalModel
                    {
                        name = model.animal.race,
                        type = model.animal.type,
                        race = model.animal.race
                    };

                    if (file != null)
                    {
                        _imageController = new ImageController();
                        animal.photo = new List<ImageModel> { _imageController.GetImage(file) };
                    }

                    using (IDal dal = new Dal())
                        dal.addAdvertissement(DateTime.Now, model.title, model.description, animal, userId);

                    return RedirectToAction("RegisterAdvertisement", new { Message = AdvertisementMessageId.AddAdvertiseSuccess });
                }
                else
                    return View(model);
            }
            else
                return RedirectToAction("Login", "Account");
        }

        public ActionResult ConsultAdvertisementView()
        {
            IDal dal = new Dal();
            List<AdvertisementModel> advertissements = dal.getAllAdvertissements();            
            return View(advertissements);
        }

        [HttpPost]
        public ActionResult ConsultAdvertisementView(AdvertisementModel model)
        {
            List<AdvertisementModel> advertissements = null;
            IDal dal = new Dal();


            System.Collections.Specialized.NameValueCollection nvc = Request.Form;
            String keyword = nvc["keyword"];

            advertissements = dal.getAdvertissementsByKeyword(keyword);

            return View(advertissements);
        }


        public enum AdvertisementMessageId
        {
            AddAdvertiseSuccess,
            Error
        }

        // GET: Advertisement
        public ActionResult Index()
        {
            return View();
        }

        // GET: Advertisement/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
       
        // GET: Advertisement/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Advertisement/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Advertisement/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Advertisement/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Views/Shared/_Foundation.cshtml
<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8" />

    @*Set the viewport width to device width for mobile *@
    <meta name="viewport" content="width=device-width" />

    <title>@ViewBag.Title - Welcome to Foundation</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @Styles.Render("~/Content/foundation/css")

    @RenderSection("head", required: false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()
    @* Zepto polyfill: If you need to support Internet Explorer, you can fall back on jQuery. http://zeptojs.com/ *@
    <script>
        document.write('<script src=' +
        ('__proto__' in {} ? '@Url.Content("~/scripts/zepto.js")' : '@Url.Content("~/scripts/jquery.js")') +
      '><\/script>')
    </script>

    @Scripts.Render("~/bundles/foundation")
    <script>
        $(document).foundation();
    </script>
    @*Use the Scripts section to define page specific scripts*@
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Petcare" content="Pet exchange">
    <meta name="Gissel, Dieulin and Sofiane" content="">

    <title>@ViewBag.Title | Petcare</title>

    <!-- inclusion des bundle -->
    @Styles.Render("~/Content/foundationCSS")
</head>
<body>

<!-- section d'entete -->
    <div class="row">
        <div class="large-12 columns">
            <!-- nav-bar -->
            <div class="nav-bar right">
                <ul class="button-group">
                    <li>
                        @Html.ActionLink("Accueil", "Index", "Home", routeValues: null, htmlAttributes: new { @class = "button" })
                    </li>
                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            @Html.AntiForgeryToken()
                            <li>
                                @Html.ActionLink("Ajoutez une annonce", "RegisterAdvertisement", "Advertisement", routeValues: null, htmlAttributes: new { @class = "button" })
                            </li>
                        }
                    }
                    <li>
                        @Html.ActionLink("Consultez les annonces", "ConsultAdvertisementView", "Advertisement", routeValues: null, htmlAttributes: new { @class = "button" })
                    </li>
                </ul>
            </div>
            <!-- End nav-bar -->

            <img src="@Url.Content("~/Content/Petcare/img/logo2.png")" alt="Acceuil" height="400" width="400" margin-top="20" />
            <hr />
            
            <!-- Liens connexion/ deconnexion  -->
            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                {
                    @Html.AntiForgeryToken()

                    <ul class="right breadcrumbs">
                        @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                        <a href="javascript:document.getElementById('logoutForm').submit()">Déconnexion</a>
                    </ul>
                }
            }
            else
            {
                <ul class="right breadcrumbs">
                    @Html.ActionLink("S'inscrire", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })
                    @Html.ActionLink("Connexion", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
                </ul>
            }

            <!-- End liens connexion/ deconnexion -->
        </div>
    </div>
    <!-- End section d'entete -->
    
    <!-- Content -->
    <div class="row">
        <div class="large-12 columns">
            @RenderBody()
        </div>
    </div>
    <!-- End Content -->

    <!-- Footer -->
    <footer class="row">
        <div class="large-12 columns">
            <hr />
            <div class="row">
                <div class="large-6 columns">
                    <p>Dieulin, Gissel & Sofiane | Master 2 IAGL - @DateTime.Now.Year</p>
                </div>
                <div class="large-6 columns">
                    <ul class="inline-list right">
                        <li>@Html.ActionLink("A propos de nous", "AboutUs", "Home", routeValues: null, htmlAttributes: new { title = "Manage" })</li>                        
                        <li>@Html.ActionLink("A propos de Petcare", "AboutPetcare", "Home", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer -->

    <!-- include bundles -->
    @Scripts.Render("~/bundles/foundationJS")

    <!-- reserve l'espace pour qu'une vue ecrive du contenu -->
    @RenderSection("scripts", required: false)
</body>
</html>